### ISSUE TITLE
When building all 'menus' expect 3 args

### ISSUE THREAD

**Issue by twimjeeni** [xackery/eqcleanup#37]
When I built eqcleanup all the 'menu.go' files (in all folders--era,core,misc,tools,zone) expected 3 arguments:

`menuOptions := menu.NewMenuOptions("'menu' for help [system]> ", 0)`

error said something along those lines of 'expected (string, int, string) but found (string, number)'...

I just went ahead and changed the line in each file to read:

`menuOptions := menu.NewMenuOptions("'menu' for help [system]> ", 0, "temp")`

I realize this is not a real fix, I wanted to reference it here for anyone who was trying to build the most recent version (to get around the xml/json error which occur when using the binaries from current available releases)

**Comment by xackery** [comment]
i didn't reailze there was traction on this repo, interesting!
I probably should touch this again - it's been 2 years since the last commit, i'll review your PR's.

**Comment by xackery** [comment]
i'm going to close this as i'll be rewriting the menu system. :)

**Comment by twimjeeni** [comment]
Awesome, your contributions to eqemu are great.  I was hoping to learn more about coding via eqemu but i got kinda lost in the complexity of it, anyways I'm glad you decided to keep it up. I was curious if you would be able to provide some advice for staying on track when selecting a project to work on to learn more for someone who has basic programming experience (c++, python)?

I've never contributed to a project on github, hoping to do it more!

thanks,

twim
________________________________

**Comment by xackery** [comment]
eqcleanup is starting to get clumped into this: https://github.com/xackery/peq-expansions

i'm taking on the task of locking PEQ into various expansions, and allowing you to run small scripts to enable/disable specific features is the hope.

As to your question, well, the best is to do testing/code review for another person's task and learn what they're doing and how they're doing it. You'll boost their productivity and debugging and learn a ton, without hitting a ton of walls you will on your own pace. Plus, you'll build a relationship with someone who will be happy to help you out as you get stuck on the harder problems.
